<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Helhum\\Typo3Console\\Composer\\PopulateCommands' => $typo3InstallDir . 'typo3conf/ext/typo3_console/Classes/Console/Composer/PopulateCommands.php',
    'Helhum\\Typo3Console\\Hook\\ExtensionInstallation' => $typo3InstallDir . 'typo3conf/ext/typo3_console/Classes/Console/Hook/ExtensionInstallation.php',
    'NITSAN\\NsBasetheme\\Controller\\NsBasethemeModuleController' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/Controller/NsBasethemeModuleController.php',
    'NITSAN\\NsBasetheme\\DataProcessing\\DefaultProcessor' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/DataProcessing/DefaultProcessor.php',
    'NITSAN\\NsBasetheme\\Domain\\Repository\\NsBasethemeRepository' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/Domain/Repository/NsBasethemeRepository.php',
    'NITSAN\\NsBasetheme\\ExpressionLanguage\\CheckContainerExtension' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/ExpressionLanguage/CheckContainerExtension.php',
    'NITSAN\\NsBasetheme\\Hooks\\BackendUserLogin' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/Hooks/BackendUserLogin.php',
    'NITSAN\\NsBasetheme\\Hooks\\CmsLayout' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/Hooks/CmsLayout.php',
    'NITSAN\\NsBasetheme\\Hooks\\SaveCloseHook' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/Hooks/SaveCloseHook.php',
    'NITSAN\\NsBasetheme\\NsBasethemeUtility' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/NsBasethemeUtility.php',
    'NITSAN\\NsBasetheme\\NsTemplate\\ExtendedTemplateService' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/NsTemplate/ExtendedTemplateService.php',
    'NITSAN\\NsBasetheme\\NsTemplate\\Parser\\StringUtility' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/NsTemplate/Parser/StringUtility.php',
    'NITSAN\\NsBasetheme\\NsTemplate\\Parser\\TypoScriptParser' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/NsTemplate/Parser/TypoScriptParser.php',
    'NITSAN\\NsBasetheme\\NsTemplate\\TemplateService' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/NsTemplate/TemplateService.php',
    'NITSAN\\NsBasetheme\\NsTemplate\\TypoScriptTemplateConstantEditorModuleFunctionController' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/NsTemplate/TypoScriptTemplateConstantEditorModuleFunctionController.php',
    'NITSAN\\NsBasetheme\\Setup' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/Setup.php',
    'NITSAN\\NsBasetheme\\Utility\\Tinysource' => $typo3InstallDir . 'typo3conf/ext/ns_basetheme/Classes/Utility/Tinysource.php',
);
