services:
  NITSAN\NsBasetheme\Setup:
    tags:
      - name: event.listener
        identifier: 'ns-basetheme-after'
        method: 'executeOnSignalAfter'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
